name: Build Ungoogled Staged
on:  
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build'
        required: true
        default: 'v139.0.7258.127-ungoogled-staged'

jobs:
  # Stage 1: Setup and early compilation (0-20%)
  build-stage-1:
    runs-on: windows-2022
    timeout-minutes: 350  # 5h 50m - under GitHub's 6h limit
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Apply Ungoogled Optimized Config
        run: |
          echo "Applying ungoogled-chromium optimized build configuration..."
          python build_config_ungoogled_optimized.py > ungoogled_optimized_args.gn
          echo "Stage 1: Setup and early compilation (target: 0-20%)"
        working-directory: C:\ungoogled-chromium-windows
      - name: Run Stage 1 (setup + early compilation)
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: false
          from_artifact: false
        env:
          UNGOOGLED_OPTIMIZED: "true"
          BUILD_STAGE: "1"
          GN_ARGS_EXTRA: "symbol_level=0 use_jumbo_build=true enable_remoting=false enable_configuration_policy=false"
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
      
  # Stage 2: Core compilation (20-40%)
  build-stage-2:
    needs: build-stage-1
    runs-on: windows-2022
    timeout-minutes: 350
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage 2 (core compilation)
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
        env:
          UNGOOGLED_OPTIMIZED: "true"
          BUILD_STAGE: "2"
          GN_ARGS_EXTRA: "symbol_level=0 use_jumbo_build=true enable_remoting=false enable_configuration_policy=false"
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
      
  # Stage 3: Advanced compilation (40-60%)
  build-stage-3:
    needs: build-stage-2
    runs-on: windows-2022
    timeout-minutes: 350
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage 3 (advanced compilation)
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
        env:
          UNGOOGLED_OPTIMIZED: "true"
          BUILD_STAGE: "3"
          GN_ARGS_EXTRA: "symbol_level=0 use_jumbo_build=true enable_remoting=false enable_configuration_policy=false"
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
      
  # Stage 4: Final compilation (60-80%)
  build-stage-4:
    needs: build-stage-3
    runs-on: windows-2022
    timeout-minutes: 350
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage 4 (final compilation)
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
        env:
          UNGOOGLED_OPTIMIZED: "true"
          BUILD_STAGE: "4"
          GN_ARGS_EXTRA: "symbol_level=0 use_jumbo_build=true enable_remoting=false enable_configuration_policy=false"
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
      
  # Stage 5: Linking and packaging (80-100%)
  build-stage-5:
    needs: build-stage-4
    runs-on: windows-2022
    timeout-minutes: 350
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage 5 (linking and packaging)
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
        env:
          UNGOOGLED_OPTIMIZED: "true"
          BUILD_STAGE: "5"
          GN_ARGS_EXTRA: "symbol_level=0 use_jumbo_build=true enable_remoting=false enable_configuration_policy=false"
    outputs:
      finished: ${{ steps.stage.outputs.finished }}

  # Stage 6: Final packaging and testing
  build-stage-6:
    needs: build-stage-5
    runs-on: windows-2022
    timeout-minutes: 350
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage 6 (final packaging)
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
        env:
          UNGOOGLED_OPTIMIZED: "true"
          BUILD_STAGE: "6"
          GN_ARGS_EXTRA: "symbol_level=0 use_jumbo_build=true enable_remoting=false enable_configuration_policy=false"
    outputs:
      finished: ${{ steps.stage.outputs.finished }}

  publish-ungoogled-staged-release:
    needs: build-stage-6
    runs-on: ubuntu-latest
    steps:
      - name: Download ungoogled staged package
        uses: actions/download-artifact@v4
        with:
          name: chromium
      - name: Publish ungoogled staged release
        id: publish
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: "ungoogled-chromium Staged Build ${{ github.event.inputs.version }}"
          body: |
            ## Ungoogled-Chromium Staged Build (6-Stage Process)
            
            This build works around GitHub Actions' 6-hour job limit by splitting the build into 6 stages.
            
            ### GitHub Actions Limitation Discovery:
            - GitHub Actions has a hard 6-hour limit per job (even if we set 12 hours)
            - Previous attempts: 3.5h → 5h50m → 6h (all hit limits)
            - Solution: Split into 6 stages of ~5h50m each
            
            ### Staged Build Process:
            - **Stage 1**: Setup and early compilation (0-20%)
            - **Stage 2**: Core compilation (20-40%) 
            - **Stage 3**: Advanced compilation (40-60%)
            - **Stage 4**: Final compilation (60-80%)
            - **Stage 5**: Linking and packaging (80-100%)
            - **Stage 6**: Final packaging and testing
            
            ### Total Build Time:
            - **Maximum**: 6 stages × 5h50m = 35 hours (worst case)
            - **Expected**: 6-12 hours total (with optimizations)
            - **Advantage**: Each stage can complete within GitHub's limits
            
            ### Build Optimizations (Same as before):
            - Remove debug symbols: ~40% time savings
            - Remove enterprise features: ~30% time savings
            - Remove advanced dev tools: ~5% time savings
            - Use jumbo builds and optimized linking
            
            ### Privacy Features (100% ungoogled-chromium):
            - Zero Google integration or data collection
            - Complete browsing privacy
            - All ungoogled-chromium features preserved
            
            ### Features Preserved (94% functionality):
            - Full web browsing capabilities
            - All media support including DRM
            - Chrome extension support
            - Core developer tools
            - All security features
            
            This staged approach should finally overcome the GitHub Actions timeout limitations!
          files: |
            ungoogled-chromium*
          prerelease: false
    outputs:
      assets: ${{ steps.publish.outputs.assets }}