name: Build ungoogled-chromium
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build'
        required: true
        default: 'v139.0.7258.127-custom-1'

jobs:
  build-1:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: false
          from_artifact: false
    outputs:
      finished: ${{ steps.stage.outputs.finished }}